const level1 = new Level(
  [
    new Pufferfish(4 * 719),
    new Pufferfish(4 * 719),
    new Pufferfish(4 * 719),
    new Pufferfish(4 * 719),
    new Endboss(4 * 719),
  ],
  [new Stone1(), new Stone2(), new Stone1()],
  [
    new BackgroundObject('img/3. Background/Layers/5. Water/L2.png', -719),
    new BackgroundObject('img/3. Background/Layers/1. Light/2.png', -719),
    new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L2.png', -719),
    new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L2.png', -719),
    new BackgroundObject('img/3. Background/Layers/2. Floor/L2.png', -719),
    new BackgroundObject('img/3. Background/Layers/5. Water/L1.png', 0),
    new BackgroundObject('img/3. Background/Layers/1. Light/1.png', 0),
    new BackgroundObject('img/3. Background/Layers/4.Fondo 2/L1.png', 0),
    new BackgroundObject('img/3. Background/Layers/3.Fondo 1/L1.png', 0),
    new BackgroundObject('img/3. Background/Layers/2. Floor/L1.png', 0),
  ],
  4,
  [
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
    new pickableObject(4 * 719, 'img/4. Marcadores/1. Coins/3.png'),
  ]
);
